apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  labels:
    app: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: 123860609515.dkr.ecr.ap-east-1.amazonaws.com/demoapp:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always